model:
  num_epochs: 10
  num_samples: 128
  num_layers: 4
  hidden_dim: 128  # Default for GPU
  device: auto  # Automatically select GPU if available, else CPU
  cpu_hidden_dim: 32  # Hidden dimension if running on CPU